using brainflow;
using System.ComponentModel;

namespace Bonsai.BrainFlow
{
    [Description("Captures synthetic data generated by the BrainFlow API without requiring external hardware.")]
    public class SyntheticBoard : BrainFlowBoard
    {
        internal override BoardIds ConfigureBoard(BrainFlowInputParams inputParams)
        {
            return BoardIds.SYNTHETIC_BOARD;
        }
    }
}
